<<<<<<< HEAD:tests/endpoint/multiple_invalid_users_failing_to_authenticate_from_host_using_kerberos.test.yml
name: Multiple Invalid Users Failing To Authenticate From Host Using Kerberos Unit
  Test
tests:
- name: Multiple Invalid Users Failing To Authenticate From Host Using Kerberos
  file: endpoint/multiple_invalid_users_failing_to_authenticate_from_host_using_kerberos.yml
=======
name: Windows Invalid Users Failed Authentication via Kerberos Unit Test
tests:
- name: Windows Invalid Users Failed Authentication via Kerberos
  file: endpoint/windows_invalid_users_failed_authentication_via_kerberos.yml
>>>>>>> updates to all ymls with error:tests/endpoint/windows_invalid_users_failed_authentication_via_kerberos.test.yml
  pass_condition: '| stats count | where count > 0'
  earliest_time: -24h
  latest_time: now
  attack_data:
  - file_name: windows-security.log
    data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1110.003/purplesharp_invalid_users_kerberos/windows-security.log
    source: WinEventLog:Security
    sourcetype: WinEventLog
